name: manage-azure-policy-84c71490
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Configure_Cosmos_DB_database_accounts_to_disable_local_authentication_dc2d41d1-4ab1-4666-a3e1-3d51c43e0049/**'
#      - .github/workflows/manage-azure-policy-84c71490.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_84c71490}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Configure_Cosmos_DB_database_accounts_to_disable_local_authentication_dc2d41d1-4ab1-4666-a3e1-3d51c43e0049/**
